import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="antialiased font-sans bg-[#eee] dark:bg-[#121212] text-black dark:text-[#E0E0E0] overflow-x-hidden transition-colors duration-300">
        
        {/* 신규 메인 헤더 */}
        <Header />
        
        {/* 전체 레이아웃 래퍼 */}
        <div className="w-full relative">
          {children}

          {/* 글로벌 사이드바 (우측에서 열림/닫힘에 따라 fixed 위치 비율 제어) */}
          <Sidebar />
        </div>
      </body>
    </html>
  );
}
